source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UITextFieldUtilityPro_Example', :exclusive => true do
  pod 'UITextFieldUtilityPro', :path => '../'
end

target 'UITextFieldUtilityPro_Tests', :exclusive => true do
  pod 'UITextFieldUtilityPro', :path => '../'

  
end
